

/****** Object:  Table [DZTPLA].[SYS_GROUP]    Script Date: 2018-12-08 오전 11:12:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [DZTPLA].[SYS_GROUP](
	[C_CODE] [char](4) NOT NULL,
	[GROUP_CODE] [varchar](10) NOT NULL,
	[GROUP_NAME] [varchar](80) NULL,
	[M_SELECT] [char](1) NOT NULL,
	[M_INSERT] [char](1) NOT NULL,
	[M_DELETE] [char](1) NOT NULL,
	[M_UPDATE] [char](1) NOT NULL,
	[M_PRINT] [char](1) NOT NULL,
 CONSTRAINT [PK_SYS_GROUP] PRIMARY KEY NONCLUSTERED 
(
	[C_CODE] ASC,
	[GROUP_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



/****** Object:  Table [DZTPLA].[G_MENU]    Script Date: 2018-12-08 오전 11:25:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [DZTPLA].[VBASE_G_MENU](
	[C_CODE] [char](4) NOT NULL,
	[GROUP_CODE] [varchar](10) NOT NULL,
	[MENU_ID] [char](12) NOT NULL,
	[MENU_POS] [varchar](12) NOT NULL,
 CONSTRAINT [PK_G_MENU] PRIMARY KEY NONCLUSTERED 
(
	[C_CODE] ASC,
	[GROUP_CODE] ASC,
	[MENU_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
