SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE DZTPLA.[CHECKD](
	[CHECK_CODE] [char](3) NOT NULL,
	[CHECKD_CODE] [varchar](3) NOT NULL,
	[C_CODE] [varchar](4) NOT NULL,
	[CHECKD_NAME] [varchar](30) NULL,
	[CHECKD_ETC] [varchar](80) NULL,
	[INSERT_ID] [varchar](10) NULL,
	[INSERT_DATE] [char](8) NULL,
	[MODIFY_ID] [varchar](10) NULL,
	[MODIFY_DATE] [char](8) NULL,
 CONSTRAINT [PK_CHECKD] PRIMARY KEY NONCLUSTERED 
(
	[CHECK_CODE] ASC,
	[CHECKD_CODE] ASC,
	[C_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


------

/****** Object:  Table DZTPLA.[AUTODOCU]    Script Date: 2018-12-01 오전 11:58:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE DZTPLA.[AUTODOCU](
	[DATA_GUBUN] [varchar](2) NOT NULL,
	[WRITE_DATE] [char](8) NOT NULL,
	[DATA_NO] [numeric](4, 0) NOT NULL,
	[DATA_LINE] [numeric](4, 0) NOT NULL,
	[DATA_SLIP] [numeric](4, 0) NOT NULL,
	[DEPT_CODE] [varchar](12) NOT NULL,
	[NODE_CODE] [varchar](4) NOT NULL,
	[C_CODE] [varchar](4) NOT NULL,
	[DATA_CODE] [varchar](20) NULL,
	[DOCU_STAT] [char](1) NOT NULL,
	[DOCU_TYPE] [char](2) NOT NULL,
	[DOCU_GUBUN] [char](1) NOT NULL,
	[AMT_GUBUN] [char](1) NOT NULL,
	[DR_AMT] [numeric](15, 0) NOT NULL,
	[CR_AMT] [numeric](15, 0) NOT NULL,
	[ACCT_CODE] [char](5) NOT NULL,
	[CHECK_CODE1] [char](3) NULL,
	[CHECK_CODE2] [char](3) NULL,
	[CHECK_CODE3] [char](3) NULL,
	[CHECK_CODE4] [char](3) NULL,
	[CHECK_CODE5] [char](3) NULL,
	[CHECK_CODE6] [char](3) NULL,
	[CHECK_CODE7] [char](3) NULL,
	[CHECK_CODE8] [char](3) NULL,
	[CHECK_CODE9] [char](3) NULL,
	[CHECK_CODE10] [char](3) NULL,
	[CHECKD_CODE1] [varchar](20) NULL,
	[CHECKD_CODE2] [varchar](20) NULL,
	[CHECKD_CODE3] [varchar](20) NULL,
	[CHECKD_CODE4] [varchar](20) NULL,
	[CHECKD_CODE5] [varchar](20) NULL,
	[CHECKD_CODE6] [varchar](20) NULL,
	[CHECKD_CODE7] [varchar](20) NULL,
	[CHECKD_CODE8] [varchar](20) NULL,
	[CHECKD_CODE9] [varchar](20) NULL,
	[CHECKD_CODE10] [varchar](20) NULL,
	[CHECKD_NAME1] [varchar](100) NULL,
	[CHECKD_NAME2] [varchar](100) NULL,
	[CHECKD_NAME3] [varchar](100) NULL,
	[CHECKD_NAME4] [varchar](100) NULL,
	[CHECKD_NAME5] [varchar](100) NULL,
	[CHECKD_NAME6] [varchar](100) NULL,
	[CHECKD_NAME7] [varchar](100) NULL,
	[CHECKD_NAME8] [varchar](100) NULL,
	[CHECKD_NAME9] [varchar](100) NULL,
	[CHECKD_NAME10] [varchar](100) NULL,
	[INSERT_ID] [varchar](10) NULL,
	[INSERT_DATE] [char](8) NULL,
	[MODIFY_ID] [varchar](10) NULL,
	[MODIFY_DATE] [char](8) NULL,
	[TRIGGER_ON] [char](1) NULL,
	[BAN_NODE_CODE] [varchar](4) NULL,
	[BAN_DEPT_CODE] [varchar](12) NULL,
	[BAN_DECI_DATE] [char](8) NULL,
	[BAN_DECI_NO] [numeric](4, 0) NULL,
	[BAN_LINE_NO] [numeric](4, 0) NULL,
	[BAN_SLIP_NO] [numeric](4, 0) NULL,
	[PUM_RMK] [varchar](100) NULL,
	[GROUP_YN] [char](1) NULL,
	[U_CD_ACCT] [nvarchar](20) NULL,
	[U_ROW_ID] [nvarchar](40) NULL,
	[U_ROW_NO] [nvarchar](40) NULL,
 CONSTRAINT [PK_AUTODOCU] PRIMARY KEY CLUSTERED 
(
	[DATA_GUBUN] ASC,
	[WRITE_DATE] ASC,
	[DATA_NO] ASC,
	[DATA_LINE] ASC,
	[DATA_SLIP] ASC,
	[DEPT_CODE] ASC,
	[NODE_CODE] ASC,
	[C_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE DZTPLA.[AUTODOCU] ADD  CONSTRAINT [DF_AUTODOCU_BANDECIDATE]  DEFAULT ('00000000') FOR [BAN_DECI_DATE]
GO


-----


/****** Object:  Table DZTPLA.[AUTOREV]    Script Date: 2018-12-01 오후 12:23:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE DZTPLA.[AUTOREV](
	[DATA_GUBUN] [varchar](2) NOT NULL,
	[WRITE_DATE] [char](8) NOT NULL,
	[DATA_NO] [numeric](4, 0) NOT NULL,
	[DATA_LINE] [numeric](4, 0) NOT NULL,
	[DATA_SLIP] [numeric](4, 0) NOT NULL,
	[DEPT_CODE] [varchar](12) NOT NULL,
	[NODE_CODE] [varchar](4) NOT NULL,
	[C_CODE] [varchar](4) NOT NULL,
	[DDEPT_CODE] [varchar](12) NOT NULL,
	[DNODE_CODE] [varchar](4) NOT NULL,
	[DECI_DATE] [char](8) NOT NULL,
	[DECI_NO] [numeric](4, 0) NOT NULL,
 CONSTRAINT [PK_AUTOREV] PRIMARY KEY CLUSTERED 
(
	[DATA_GUBUN] ASC,
	[WRITE_DATE] ASC,
	[DATA_NO] ASC,
	[DATA_LINE] ASC,
	[DATA_SLIP] ASC,
	[DEPT_CODE] ASC,
	[NODE_CODE] ASC,
	[C_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE DZTPLA.[AUTOREV] ADD  CONSTRAINT [DF_AUTOREV_WRITE_DATE]  DEFAULT ('00000000') FOR [WRITE_DATE]
GO

ALTER TABLE DZTPLA.[AUTOREV] ADD  CONSTRAINT [DF_AUTOREV_DATA_NO]  DEFAULT ((0)) FOR [DATA_NO]
GO

ALTER TABLE DZTPLA.[AUTOREV] ADD  CONSTRAINT [DF_AUTOREV_DATA_LINE]  DEFAULT ((0)) FOR [DATA_LINE]
GO

ALTER TABLE DZTPLA.[AUTOREV] ADD  CONSTRAINT [DF_AUTOREV_DATA_SLIP]  DEFAULT ((0)) FOR [DATA_SLIP]
GO

ALTER TABLE DZTPLA.[AUTOREV]  WITH CHECK ADD CHECK  (([DECI_DATE]='00000000' OR [DECI_DATE]>'19500101' AND [DECI_DATE]<'21000101' AND CONVERT([datetime],[DECI_DATE])=CONVERT([datetime],[DECI_DATE])))
GO

ALTER TABLE DZTPLA.[AUTOREV]  WITH CHECK ADD CHECK  (([WRITE_DATE]='00000000' OR [WRITE_DATE]>'19500101' AND [WRITE_DATE]<'21000101' AND CONVERT([datetime],[WRITE_DATE])=CONVERT([datetime],[WRITE_DATE])))
GO


-----


/****** Object:  Table DZTPLA.[BILLRELA]    Script Date: 2018-12-01 오후 12:25:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE DZTPLA.[BILLRELA](
	[DATA_GUBUN] [varchar](2) NOT NULL,
	[WRITE_DATE] [char](8) NOT NULL,
	[DATA_NO] [numeric](4, 0) NOT NULL,
	[DATA_LINE] [numeric](4, 0) NOT NULL,
	[DATA_SLIP] [numeric](4, 0) NOT NULL,
	[DEPT_CODE] [varchar](12) NOT NULL,
	[NODE_CODE] [varchar](4) NOT NULL,
	[C_CODE] [varchar](4) NOT NULL,
	[BILL_NO] [varchar](20) NOT NULL,
	[SUGUM_TYPE] [char](1) NULL,
	[VEN_CODE] [varchar](6) NULL,
	[DEPT_CODE2] [varchar](12) NULL,
	[SA_CODE] [varchar](10) NULL,
	[SUGUM_DATE] [char](8) NOT NULL,
	[SILMUL_DEPT_CODE] [varchar](12) NULL,
	[BILL_TYPE] [char](1) NULL,
	[ISS_DATE] [char](8) NOT NULL,
	[DUE_DATE] [char](8) NOT NULL,
	[BANK_CODE] [varchar](3) NULL,
	[ISS] [varchar](20) NULL,
	[P_ENDORSE] [varchar](20) NULL,
	[BILL_AMT] [numeric](15, 0) NOT NULL,
	[BANK_JUM] [varchar](30) NULL,
	[BANK_CODE2] [varchar](3) NULL,
	[BANK_JUM2] [varchar](30) NULL,
	[SUTAK_DATE] [char](8) NULL,
	[FUND_CODE] [varchar](20) NULL,
	[BILL_CON] [char](1) NOT NULL,
	[DEAL_DATE] [char](8) NULL,
 CONSTRAINT [PK_BILLRELA] PRIMARY KEY CLUSTERED 
(
	[DATA_GUBUN] ASC,
	[WRITE_DATE] ASC,
	[DATA_NO] ASC,
	[DATA_LINE] ASC,
	[DATA_SLIP] ASC,
	[DEPT_CODE] ASC,
	[NODE_CODE] ASC,
	[C_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE DZTPLA.[BILLRELA] ADD  CONSTRAINT [DF_BILLRELA_WRITE_DATE]  DEFAULT ('00000000') FOR [WRITE_DATE]
GO

ALTER TABLE DZTPLA.[BILLRELA] ADD  CONSTRAINT [DF_BILLRELA_DATA_NO]  DEFAULT ((0)) FOR [DATA_NO]
GO

ALTER TABLE DZTPLA.[BILLRELA] ADD  CONSTRAINT [DF_BILLRELA_DATA_LINE]  DEFAULT ((0)) FOR [DATA_LINE]
GO

ALTER TABLE DZTPLA.[BILLRELA] ADD  CONSTRAINT [DF_BILLRELA_DATA_SLIP]  DEFAULT ((0)) FOR [DATA_SLIP]
GO

ALTER TABLE DZTPLA.[BILLRELA] ADD  CONSTRAINT [DF_BILLRELA_BILL_CON]  DEFAULT ('1') FOR [BILL_CON]
GO

ALTER TABLE DZTPLA.[BILLRELA]  WITH CHECK ADD CHECK  (([DUE_DATE]='00000000' OR [DUE_DATE]>'19500101' AND [DUE_DATE]<'21000101' AND CONVERT([datetime],[DUE_DATE])=CONVERT([datetime],[DUE_DATE])))
GO

ALTER TABLE DZTPLA.[BILLRELA]  WITH CHECK ADD CHECK  (([ISS_DATE]='00000000' OR [ISS_DATE]>'19500101' AND [ISS_DATE]<'21000101' AND CONVERT([datetime],[ISS_DATE])=CONVERT([datetime],[ISS_DATE])))
GO

ALTER TABLE DZTPLA.[BILLRELA]  WITH CHECK ADD CHECK  (([SUGUM_DATE]='00000000' OR [SUGUM_DATE]>'19500101' AND [SUGUM_DATE]<'21000101' AND CONVERT([datetime],[SUGUM_DATE])=CONVERT([datetime],[SUGUM_DATE])))
GO

ALTER TABLE DZTPLA.[BILLRELA]  WITH CHECK ADD CHECK  (([SUTAK_DATE]='00000000' OR [SUTAK_DATE]>'19500101' AND [SUTAK_DATE]<'21000101' AND CONVERT([datetime],[SUTAK_DATE])=CONVERT([datetime],[SUTAK_DATE])))
GO

ALTER TABLE DZTPLA.[BILLRELA]  WITH CHECK ADD CHECK  (([WRITE_DATE]='00000000' OR [WRITE_DATE]>'19500101' AND [WRITE_DATE]<'21000101' AND CONVERT([datetime],[WRITE_DATE])=CONVERT([datetime],[WRITE_DATE])))
GO


----


/****** Object:  Table DZTPLA.[GUBUNACCT]    Script Date: 2018-12-01 오후 12:27:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE DZTPLA.[GUBUNACCT](
	[ACCT_CODE] [char](5) NOT NULL,
	[GUBUN_CODE] [char](2) NOT NULL,
	[C_CODE] [varchar](4) NOT NULL,
	[GUBUN] [char](1) NULL,
 CONSTRAINT [PK_GUBUNACCT] PRIMARY KEY CLUSTERED 
(
	[ACCT_CODE] ASC,
	[C_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

----


/****** Object:  Table DZTPLA.[TAXRELA]    Script Date: 2018-12-01 오후 12:28:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE DZTPLA.[TAXRELA](
	[DATA_GUBUN] [varchar](2) NOT NULL,
	[WRITE_DATE] [char](8) NOT NULL,
	[DATA_NO] [numeric](4, 0) NOT NULL,
	[DATA_LINE] [numeric](4, 0) NOT NULL,
	[DATA_SLIP] [numeric](4, 0) NOT NULL,
	[DEPT_CODE] [varchar](12) NOT NULL,
	[NODE_CODE] [varchar](4) NOT NULL,
	[C_CODE] [varchar](4) NOT NULL,
	[BAL_DATE] [char](8) NULL,
	[VEN_TYPE] [char](1) NULL,
	[TAX_GU] [char](2) NULL,
	[GONG_AMT] [numeric](15, 0) NULL,
	[TAX_VAT] [numeric](15, 0) NULL,
	[VEN_CODE] [char](6) NULL,
	[S_IDNO] [varchar](15) NULL,
	[GONG_AMT2] [numeric](15, 0) NULL,
	[BUL_GUBUN] [char](1) NULL,
	[MSUM_YN] [char](1) NULL,
	[EXPORT_NO] [char](15) NULL,
	[EXCH_CODE] [char](3) NULL,
	[EXCH_RATE] [numeric](15, 4) NOT NULL,
	[EXCH_AMT] [numeric](15, 2) NOT NULL,
	[EJE_RATE] [char](1) NULL,
	[CARDNO] [varchar](20) NULL,
	[CUSTOM_NO] [char](10) NULL,
	[CASH_NUM] [varchar](9) NULL,
	[RELAT_NO] [varchar](30) NULL,
	[PRT] [char](1) NULL,
	[DAY_PRINT] [char](8) NULL,
	[TAX_AMT2] [numeric](15, 0) NOT NULL,
	[PJT_CODE] [varchar](12) NULL,
	[EJE_ITEM] [varchar](30) NULL,
	[EJE_QT] [numeric](15, 0) NULL,
	[EJE_AMT] [numeric](15, 0) NULL,
	[RMK] [varchar](100) NULL,
	[ETAX_KEY] [varchar](20) NULL,
	[ETAX_STAT] [varchar](2) NULL,
	[JEONJA_YN] [char](1) NULL,
	[MODIFY_CODE] [char](2) NULL,
	[BAN_ETAX_KEY] [varchar](20) NULL,
	[SALE_ETAX_KEY] [varchar](40) NULL,
 CONSTRAINT [PK_TAXRELA] PRIMARY KEY CLUSTERED 
(
	[DATA_GUBUN] ASC,
	[WRITE_DATE] ASC,
	[DATA_NO] ASC,
	[DATA_LINE] ASC,
	[DATA_SLIP] ASC,
	[DEPT_CODE] ASC,
	[NODE_CODE] ASC,
	[C_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE DZTPLA.[TAXRELA] ADD  CONSTRAINT [DF_TAXRELA_WRITE_DATE]  DEFAULT ('00000000') FOR [WRITE_DATE]
GO

ALTER TABLE DZTPLA.[TAXRELA] ADD  CONSTRAINT [DF_TAXRELA_DATA_NO]  DEFAULT ((0)) FOR [DATA_NO]
GO

ALTER TABLE DZTPLA.[TAXRELA] ADD  CONSTRAINT [DF_TAXRELA_DATA_LINE]  DEFAULT ((0)) FOR [DATA_LINE]
GO

ALTER TABLE DZTPLA.[TAXRELA] ADD  CONSTRAINT [DF_TAXRELA_DATA_SLIP]  DEFAULT ((0)) FOR [DATA_SLIP]
GO

ALTER TABLE DZTPLA.[TAXRELA] ADD  CONSTRAINT [DF__TAXRELA__MSUM_YN__396371BC]  DEFAULT ('1') FOR [MSUM_YN]
GO

ALTER TABLE DZTPLA.[TAXRELA] ADD  CONSTRAINT [DF__TAXRELA__EXCH_RA__3A5795F5]  DEFAULT ((0)) FOR [EXCH_RATE]
GO

ALTER TABLE DZTPLA.[TAXRELA] ADD  CONSTRAINT [DF__TAXRELA__EXCH_AM__3B4BBA2E]  DEFAULT ((0)) FOR [EXCH_AMT]
GO

ALTER TABLE DZTPLA.[TAXRELA] ADD  CONSTRAINT [DF_TAXRELA_DAYPRINT]  DEFAULT ('00000000') FOR [DAY_PRINT]
GO

ALTER TABLE DZTPLA.[TAXRELA] ADD  CONSTRAINT [DF__TAXRELA__TAX_AMT__5689C04F]  DEFAULT ((0)) FOR [TAX_AMT2]
GO

ALTER TABLE DZTPLA.[TAXRELA]  WITH CHECK ADD CHECK  (([BAL_DATE]='00000000' OR [BAL_DATE]>'19500101' AND [BAL_DATE]<'21000101' AND CONVERT([datetime],[BAL_DATE])=CONVERT([datetime],[BAL_DATE])))
GO

ALTER TABLE DZTPLA.[TAXRELA]  WITH CHECK ADD CHECK  (([WRITE_DATE]='00000000' OR [WRITE_DATE]>'19500101' AND [WRITE_DATE]<'21000101' AND CONVERT([datetime],[WRITE_DATE])=CONVERT([datetime],[WRITE_DATE])))
GO


----------

/****** Object:  Table DZTPLA.[TAXRELA2]    Script Date: 2018-12-01 오후 12:28:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE DZTPLA.[TAXRELA2](
	[DATA_GUBUN] [varchar](2) NOT NULL,
	[WRITE_DATE] [char](8) NOT NULL,
	[DATA_NO] [numeric](4, 0) NOT NULL,
	[DATA_LINE] [numeric](4, 0) NOT NULL,
	[DATA_SLIP] [numeric](4, 0) NOT NULL,
	[DEPT_CODE] [varchar](12) NOT NULL,
	[NODE_CODE] [varchar](4) NOT NULL,
	[C_CODE] [varchar](4) NOT NULL,
	[TAXSUB_NO] [numeric](1, 0) NOT NULL,
	[MONDAY] [char](4) NULL,
	[PUMMOK] [varchar](100) NULL,
	[MU_SIZE] [varchar](20) NULL,
	[QTY] [numeric](15, 4) NULL,
	[PRICE] [numeric](15, 4) NULL,
	[SUPPLY_PRICE] [numeric](15, 4) NULL,
	[VAT_PRICE] [numeric](15, 0) NULL,
	[BIGO] [varchar](20) NULL,
 CONSTRAINT [PK_TEXRELA2] PRIMARY KEY CLUSTERED 
(
	[TAXSUB_NO] ASC,
	[DATA_GUBUN] ASC,
	[WRITE_DATE] ASC,
	[DATA_NO] ASC,
	[DATA_LINE] ASC,
	[DATA_SLIP] ASC,
	[DEPT_CODE] ASC,
	[NODE_CODE] ASC,
	[C_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE DZTPLA.[TAXRELA2] ADD  CONSTRAINT [DF_TAXRELA2_WRITE_DATE]  DEFAULT ('00000000') FOR [WRITE_DATE]
GO

ALTER TABLE DZTPLA.[TAXRELA2] ADD  CONSTRAINT [DF_TAXRELA2_DATA_NO]  DEFAULT ((0)) FOR [DATA_NO]
GO

ALTER TABLE DZTPLA.[TAXRELA2] ADD  CONSTRAINT [DF_TAXRELA2_DATA_LINE]  DEFAULT ((0)) FOR [DATA_LINE]
GO

ALTER TABLE DZTPLA.[TAXRELA2] ADD  CONSTRAINT [DF_TAXRELA2_DATA_SLIP]  DEFAULT ((0)) FOR [DATA_SLIP]
GO

ALTER TABLE DZTPLA.[TAXRELA2]  WITH CHECK ADD CHECK  (([WRITE_DATE]='00000000' OR [WRITE_DATE]>'19500101' AND [WRITE_DATE]<'21000101' AND CONVERT([datetime],[WRITE_DATE])=CONVERT([datetime],[WRITE_DATE])))
GO


---------


/****** Object:  Table DZTPLA.[SYS_DW_ATTRIBUTES]    Script Date: 2018-12-01 오후 12:30:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE DZTPLA.[SYS_DW_ATTRIBUTES](
	[c_code] [char](4) NOT NULL,
	[sno] [varchar](10) NOT NULL,
	[menu_id] [varchar](12) NOT NULL,
	[datawindow_name] [varchar](60) NOT NULL,
	[tab_name] [varchar](40) NOT NULL,
	[object_type] [varchar](30) NOT NULL,
	[object_code] [varchar](100) NOT NULL,
	[object_name] [varchar](100) NULL,
	[default_tab] [char](1) NULL,
	[visible] [varchar](250) NULL,
	[x] [numeric](10, 4) NULL,
	[y] [numeric](10, 4) NULL,
	[width] [numeric](10, 4) NULL,
	[height] [numeric](10, 4) NULL,
	[band] [varchar](20) NULL,
	[edit_limit] [numeric](4, 0) NULL,
	[alignment] [char](1) NULL,
	[tabsequence] [numeric](8, 0) NULL,
	[format] [varchar](250) NULL,
	[coltype] [varchar](20) NULL,
	[dbname] [varchar](60) NULL,
	[col_values] [varchar](250) NULL,
	[object_desc] [varchar](250) NULL,
	[col_id] [numeric](4, 0) NULL,
	[col_edit_style] [varchar](20) NULL,
	[col_checkbox_on] [varchar](20) NULL,
	[col_checkbox_off] [varchar](20) NULL,
	[col_editmask_mask] [varchar](100) NULL,
	[user_create] [char](1) NULL,
 CONSTRAINT [PK_SYS_DW_ATTRIBUTES] PRIMARY KEY NONCLUSTERED 
(
	[c_code] ASC,
	[sno] ASC,
	[menu_id] ASC,
	[datawindow_name] ASC,
	[tab_name] ASC,
	[object_type] ASC,
	[object_code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


----

/****** Object:  Table DZTPLA.[SYS_DW_PRINT]    Script Date: 2018-12-01 오후 12:31:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE DZTPLA.[SYS_DW_PRINT](
	[c_code] [char](4) NOT NULL,
	[sno] [varchar](10) NOT NULL,
	[menu_id] [varchar](12) NOT NULL,
	[datawindow_name] [varchar](60) NOT NULL,
	[tab_name] [varchar](40) NOT NULL,
	[header_height] [numeric](10, 4) NULL,
	[title_visible] [char](1) NULL,
	[title_text] [varchar](100) NULL,
	[title_x] [numeric](10, 4) NULL,
	[title_y] [numeric](10, 4) NULL,
	[title_width] [numeric](10, 4) NULL,
	[title_height] [numeric](10, 4) NULL,
	[title_font_face] [varchar](30) NULL,
	[title_font_height] [numeric](4, 0) NULL,
	[title_font_weight] [numeric](8, 0) NULL,
	[sc_visible] [char](1) NULL,
	[sc_x] [numeric](10, 4) NULL,
	[sc_y] [numeric](10, 4) NULL,
	[sc_width] [numeric](10, 4) NULL,
	[sc_height] [numeric](10, 4) NULL,
	[date_visible] [char](1) NULL,
	[date_x] [numeric](10, 4) NULL,
	[date_y] [numeric](10, 4) NULL,
	[time_visible] [char](1) NULL,
	[time_x] [numeric](10, 4) NULL,
	[time_y] [numeric](10, 4) NULL,
	[page_visible] [char](1) NULL,
	[page_x] [numeric](10, 4) NULL,
	[page_y] [numeric](10, 4) NULL,
 CONSTRAINT [PK_SYS_DW_PRINT] PRIMARY KEY NONCLUSTERED 
(
	[c_code] ASC,
	[sno] ASC,
	[menu_id] ASC,
	[datawindow_name] ASC,
	[tab_name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


------------


/****** Object:  Table DZTPLA.[DZAIS_MENU]    Script Date: 2018-12-01 오후 12:33:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE DZTPLA.[DZAIS_MENU](
	[DZAIS_ID] [varchar](60) NOT NULL,
	[MENU_ID] [varchar](12) NOT NULL,
	[FILE_NAMES] [varchar](250) NULL,
 CONSTRAINT [PK_DZAIS_MENU] PRIMARY KEY CLUSTERED 
(
	[DZAIS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-----


/****** Object:  Table [DZBASE].[COMPANYINFO]    Script Date: 2018-12-01 오후 1:49:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE DZTPLA.[COMPANYINFO](
	[C_CODE] [varchar](4) NOT NULL,
	[C_NAME] [varchar](50) NOT NULL,
	[GISU] [varchar](3) NULL,
	[FDATE] [char](8) NULL,
	[TDATE] [char](8) NULL,
	[BG_GUBUN] [char](1) NULL,
	[DNAME] [varchar](20) NULL,
	[SPOST_NO] [varchar](8) NULL,
	[S_ADDR] [varchar](100) NULL,
	[DPOST_NO] [varchar](8) NULL,
	[D_ADDR] [varchar](100) NULL,
	[BPOST_NO] [varchar](8) NULL,
	[B_ADDR] [varchar](100) NULL,
	[SNO] [char](10) NULL,
	[PNO] [char](13) NULL,
	[UPTAE] [varchar](30) NULL,
	[JONG] [varchar](30) NULL,
	[SPHONE] [varchar](20) NULL,
	[CPHONE] [varchar](20) NULL,
	[HPHONE] [varchar](20) NULL,
	[B_GUBUN] [char](1) NULL,
	[J_GUBUN] [char](1) NULL,
	[J_YN] [char](1) NULL,
	[BEGIN_YMD] [char](8) NULL,
	[STRU_YMD] [char](8) NULL,
	[CLOSE_YMD] [char](8) NULL,
	[ATDTAX] [char](3) NULL,
	[ATDTAXN] [varchar](20) NULL,
	[CTDTAX] [char](3) NULL,
	[CTDTAXN] [varchar](20) NULL,
	[DIDNO] [char](13) NULL,
	[PLACE_GUBUN] [char](1) NULL,
	[JTAXPLACE] [varchar](20) NULL,
	[TOTACCEPT_NO] [char](7) NULL,
	[NM_CMPY_E] [varchar](50) NULL,
	[DC_ADDR_E] [varchar](100) NULL,
	[FG_PROC_W] [char](1) NULL,
	[C_ENAME] [varchar](40) NULL,
	[E_ADDR] [varchar](80) NULL,
	[E_NAME] [varchar](30) NULL,
	[HOMEPAGE] [varchar](100) NULL,
	[EMP_NO_CMPY] [int] NULL,
 CONSTRAINT [PK_COMPANYINFO] PRIMARY KEY NONCLUSTERED 
(
	[C_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


